CREATE TABLE IF NOT EXISTS phrase (
    id SERIAL PRIMARY KEY,
    scene VARCHAR(255),
    phrase TEXT,
    tags TEXT[],
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
