-- AlterTable
ALTER TABLE "scenes"
ADD COLUMN     "note" TEXT NOT NULL DEFAULT '' COLLATE NOCASE,
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
